# 6/21 Today I learned...

# Namespaces, NameError is raised when variables are not found in the right hierarachy

We learned that in Python, everything is an object.

Namespaces are like dictionary with key:value set where key is the name of variables, and value is an object associated with it.

These namespaces exist in different scales of worlds.

There are 4 different namespaces depending on the scale of its scope.

### Built-in > Global > Enclosed = Local (LEGB rule)

Built-in namespaces exist in everywhere as long as we use Python.

Global namespaces exist in current file(module), and when it is running.

Local namespaces exist in functions.

Enclosing namespaces exist in functions. (When another function is created inside outer function)


# <em>Built-in namespaces</em>

In order to see built-in namespaces
```py
print(dir(__builtins__))
```


We can see all the built-in functions like `help()`, `max()`, `zip()`

We can see many exceptions which will raise when we have errors like `NameError`, `ZeroDivisionError`
```py
['ArithmeticError', 'AssertionError', 'AttributeError', 'BaseException', 'BlockingIOError', 
'BrokenPipeError', 'BufferError', 'BytesWarning', 'ChildProcessError', 'ConnectionAbortedError', 
'ConnectionError', 'ConnectionRefusedError', 'ConnectionResetError', 'DeprecationWarning', 'EOFError', 
'Ellipsis', 'EnvironmentError', 'Exception', 'False', 'FileExistsError', 'FileNotFoundError', 
'FloatingPointError', 'FutureWarning', 'GeneratorExit', 'IOError', 'ImportError', 'ImportWarning', 
'IndentationError', 'IndexError', 'InterruptedError', 'IsADirectoryError', 'KeyError', 'KeyboardInterrupt', 
'LookupError', 'MemoryError', 'ModuleNotFoundError', 'NameError', 'None', 'NotADirectoryError', 
'NotImplemented', 'NotImplementedError', 'OSError', 'OverflowError', 'PendingDeprecationWarning', 
'PermissionError', 'ProcessLookupError', 'RecursionError', 'ReferenceError', 'ResourceWarning', 
'RuntimeError', 'RuntimeWarning', 'StopAsyncIteration', 'StopIteration', 'SyntaxError', 'SyntaxWarning', 
'SystemError', 'SystemExit', 'TabError', 'TimeoutError', 'True', 'TypeError', 'UnboundLocalError', 
'UnicodeDecodeError', 'UnicodeEncodeError', 'UnicodeError', 'UnicodeTranslateError', 'UnicodeWarning', 
'UserWarning', 'ValueError', 'Warning', 'WindowsError', 'ZeroDivisionError', '__build_class__', '__debug__', 
'__doc__', '__import__', '__loader__', '__name__', '__package__', '__spec__', 'abs', 'all', 'any', 'ascii', 
'bin', 'bool', 'breakpoint', 'bytearray', 'bytes', 'callable', 'chr', 'classmethod', 'compile', 'complex', 
'copyright', 'credits', 'delattr', 'dict', 'dir', 'divmod', 'enumerate', 'eval', 'exec', 'exit', 'filter', 
'float', 'format', 'frozenset', 'getattr', 'globals', 'hasattr', 'hash', 'help', 'hex', 'id', 'input', 'int', 
'isinstance', 'issubclass', 'iter', 'len', 'license', 'list', 'locals', 'map', 'max', 'memoryview', 'min', 'next', 
'object', 'oct', 'open', 'ord', 'pow', 'print', 'property', 'quit', 'range', 'repr', 'reversed', 'round', 'set', 
'setattr', 'slice', 'sorted', 'staticmethod', 'str', 'sum', 'super', 'tuple', 'type', 'vars', 'zip']
```

# <em>Global namespaces</em>

In order to see global namespaces

```py
print(globals())
```

```py
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, 
'__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>}
```

When we added `global_variable` in this module and print `globals()`
```py
global_variable = "Hello I am a global namespace object that works only in this module!"

print(globals())
```

We can notice that there is `'global_variable': 'Hello I am a global namespace object that works only in this module!'` key:value pair.
```py
{'__name__': '__main__', '__doc__': None, '__package__': None, '__loader__': <class '_frozen_importlib.BuiltinImporter'>, 
'__spec__': None, '__annotations__': {}, '__builtins__': <module 'builtins' (built-in)>, 
'global_variable': 'Hello I am a global namespace object that works only in this module!'}
```
# <em>Local namespaces</em>
```py
def introduce_myself(name):
    print(f"I will introduce myself, my name is {name}")
    
    #print local namespaces for introduce_myself()
    print(locals())

#we have to call this function to see local namespaces for introduce_myself()    
introduce_myself("Jin")
```
And we get
```
I will introduce myself, my name is Jin
{'name': 'Jin'}
```
Notice that there is `{'name': 'Jin'}` which is a namespace for `introduce_myself()` function.

# <em>Enclosing namespaces</em>

```py
def outer_function():
    outer_value = "outer"
    print(locals())
    def inner_function():
        
        inner_value = "inner"
        
        print(locals())
    
    inner_function()
    print(locals())
    
    
outer_function()
```
In above example,

We can see that `outer_function()` nests another function called `inner_function()`.

`outer_function()` serves a role of enclosing function and `inner_function()` serves a role of enclosed function.



# NameError is raised when variables are not found in the right hierarchy

For example,
```py
def global_function(num1,num2):
    local_variable = "hello I am local"
    print(local_variable)
print(local_variable)
```

```diff
- NameError: name 'local_variable' is not defined
```
